gem 'rspec'
require 'rspec'

require '../lib/constants'
require '../lib/rule_config'
require '../lib/rules_evaluator'
require '../lib/feature_rules_evaluator'
require '../lib/step_definition'
require '../lib/feature'
require '../lib/scenario'
require '../lib/cuke_sniffer'